# Generated by Django 5.1.5 on 2025-02-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=30)),
                ('product_details', models.CharField(max_length=30)),
                ('product_photo', models.FileField(upload_to='Assets/Product/Image/')),
                ('product_amzonlink', models.CharField(max_length=60)),
                ('product_flpctlink', models.CharField(max_length=60)),
            ],
        ),
    ]
