# Generated by Django 5.1.5 on 2025-02-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='product_photo',
        ),
    ]
