# Generated by Django 5.1.5 on 2025-02-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_productskintype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('answer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_content', models.CharField(max_length=30)),
                ('news_photo', models.FileField(upload_to='Assets/News/Image/')),
            ],
        ),
    ]
