# Generated by Django 5.1.5 on 2025-03-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_info_tbl_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admin',
        ),
        migrations.DeleteModel(
            name='tbl_agelimit',
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_concern',
        ),
        migrations.DeleteModel(
            name='tbl_district',
        ),
        migrations.RemoveField(
            model_name='tbl_gallery',
            name='product',
        ),
        migrations.DeleteModel(
            name='tbl_gender',
        ),
        migrations.DeleteModel(
            name='tbl_info',
        ),
        migrations.DeleteModel(
            name='tbl_news',
        ),
        migrations.DeleteModel(
            name='tbl_productskintype',
        ),
        migrations.DeleteModel(
            name='tbl_skintype',
        ),
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
