# Generated by Django 5.1.5 on 2025-03-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_initial'),
        ('User', '0002_delete_tbl_userconcern'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_concern',
        ),
    ]
