# Generated by Django 5.1.5 on 2025-03-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_concern'),
        ('User', '0004_delete_tbl_userconcern'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_concern',
        ),
    ]
