# Generated by Django 5.1.5 on 2025-03-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_delete_tbl_concern'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_concern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern_name', models.CharField(max_length=30)),
                ('concern_details', models.CharField(max_length=50)),
                ('concern_photo', models.FileField(upload_to='Assets/Concern/Image/')),
            ],
        ),
    ]
