# Generated by Django 5.1.5 on 2025-03-04 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_concern'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='concern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_concern'),
        ),
    ]
