# Generated by Django 5.1.5 on 2025-03-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_userconcern',
        ),
    ]
