# Generated by Django 5.1.5 on 2025-03-03 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0012_tbl_concern'),
        ('Guest', '0003_initial'),
        ('User', '0002_delete_tbl_userconcern'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_userconcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_concern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
