# Generated by Django 5.1.5 on 2025-03-08 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='user',
        ),
    ]
