# Generated by Django 5.1.5 on 2025-03-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_tbl_complaint_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
